spring:
  jpa:
    open-in-view: false    
  thymeleaf:
    cache: true
  output:
    ansi:
      enabled: ALWAYS
  liquibase:
    enabled: true  
    
server:
  port: 8083
  servlet:
    context-path: /meteo-ya

maven:
  branch-name: '@scmBranch@'
  build-number: '@buildNumber@'
 
eureka:
  client:
      enabled: false          
    

   
