spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  boot:
    ##################
    #   Admin client Settings
    ##################
    admin:
      client:
        url: http://meteohost:8090/meteo-admin
        username: ${METEO_USER}
        password: ${METEO_PASSWD}
        instance:
          metadata:
            user:
              name: ${METEO_USER}
              password: ${METEO_PASSWD}
          service-base-url: http://meteohost:8090

##################
#   Server Settings
##################
server:
  port: 8083
  shutdown: graceful  # а для встроенного??
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

##################
#   Management Settings
##################
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'



