spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:meteo-ya-dev
    username: ${METEO_USER}
    password: ${METEO_PASSWD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true



