##################
#   Spring Settings
##################
spring:
  application:
    name: meteo-ya-cli
  profiles:
    active: 
      - '@spring.profiles.active@'
  output:
    ansi:
      enabled: ALWAYS

maven:
  branch-name: '@scmBranch@'
  build-number: '@buildNumber@'
  


