##################
#   Spring Settings
##################
spring:
  application:
    name: meteo-ya-cli
  profiles:
    active: 
      - '@spring.profiles.active@'
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    ROOT: WARN
    org:
      hibernate: WARN
      springframework:
        security: WARN
    ru:    
      m4j: INFO

maven:
  branch-name: '@scmBranch@'
  build-number: '@buildNumber@'
  


